-- ============================================================================
-- seed_call_scripts.sql — Modèle de script d'appel par étape du pipeline
-- Remplit la table `call_scripts` (filet utilisé par generate-call-script quand
-- aucune clé IA n'est configurée). Les agents voient ce script dans la modale
-- d'appel, adapté à l'étape du client. Variables: [nom], [agent], [agence].
-- Idempotent : remplace les scripts existants pour ces étapes.
-- ============================================================================
BEGIN;

-- Table au format single-tenant attendu par l'app (créée si absente).
CREATE TABLE IF NOT EXISTS public.call_scripts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pipeline_stage TEXT NOT NULL,
  title TEXT NOT NULL,
  intro_text TEXT DEFAULT '',
  questions JSONB DEFAULT '[]',
  outro_text TEXT DEFAULT '',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Si une colonne legacy tenant_id NOT NULL existe (ancien schéma), on la relâche.
DO $$
DECLARE v_has_tenant boolean;
BEGIN
  SELECT EXISTS(SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='call_scripts' AND column_name='tenant_id') INTO v_has_tenant;
  IF v_has_tenant THEN
    BEGIN EXECUTE 'ALTER TABLE public.call_scripts ALTER COLUMN tenant_id DROP NOT NULL';
    EXCEPTION WHEN others THEN NULL; END;
  END IF;
END $$;

-- Repart proprement pour ces 9 étapes.
DELETE FROM public.call_scripts WHERE pipeline_stage IN ('accueil', 'visite_a_gerer', 'visite_confirmee', 'visite_terminee', 'negociation', 'reservation', 'relancement', 'vente', 'perdue');

INSERT INTO public.call_scripts (pipeline_stage, title, intro_text, questions, outro_text, is_active) VALUES
  ('accueil', 'Accueil — Premier contact & qualification', 'Bonjour [nom], je suis [agent] de [agence]. Je vous appelle suite à votre intérêt pour nos programmes immobiliers. Vous avez deux minutes ? J''aimerais juste mieux comprendre votre projet pour bien vous orienter.', '[{"id": "q1", "question": "Quel type de bien recherchez-vous ?", "type": "select", "options": ["F2", "F3", "F4", "F5", "Villa", "Duplex", "Local"], "maps_to": "desired_unit_types"}, {"id": "q2", "question": "Quel budget avez-vous prévu (en DA) ?", "type": "number", "maps_to": "confirmed_budget"}, {"id": "q3", "question": "C''est pour habiter ou pour investir ?", "type": "radio", "options": ["Résidence principale", "Investissement", "Les deux"]}, {"id": "q4", "question": "Quel est votre niveau d''urgence ?", "type": "radio", "options": ["Urgent", "Dans les 3 mois", "Pas pressé / en veille"], "maps_to": "interest_level", "conditions": [{"if": "Urgent", "then_say": "Parfait, on a des unités livrables rapidement. Je vous propose une visite cette semaine."}, {"if": "Pas pressé / en veille", "then_say": "Aucun souci. Je vous envoie le catalogue et je reste à votre disposition quand vous serez prêt."}, {"if_default": true, "then_say": "Très bien, on garde le rythme qui vous convient."}]}, {"id": "q5", "question": "Comment comptez-vous financer l''achat ?", "type": "select", "options": ["Comptant", "Crédit bancaire", "Mixte", "LPP / AADL", "À définir"], "maps_to": "payment_method"}]'::jsonb, 'Merci [nom]. D''après ce que vous me dites, le mieux est qu''on organise une visite pour que vous voyiez le bien en vrai. Vous préférez en semaine ou le week-end ?', TRUE),
  ('visite_a_gerer', 'Visite à gérer — Caler le rendez-vous', 'Bonjour [nom], [agent] de [agence]. On avait convenu d''organiser une visite. Je vous appelle pour fixer la date qui vous arrange le mieux.', '[{"id": "q1", "question": "Quel moment vous conviendrait le mieux ?", "type": "select", "options": ["En semaine", "Ce week-end", "La semaine prochaine"]}, {"id": "q2", "question": "Plutôt matin ou après-midi ?", "type": "radio", "options": ["Matin", "Après-midi", "Fin de journée"]}, {"id": "q3", "question": "Vous viendrez seul ou accompagné ?", "type": "radio", "options": ["Seul", "En couple", "Avec la famille"]}, {"id": "q4", "question": "Une contrainte pour vous déplacer (transport, zone) ?", "type": "text"}, {"id": "q5", "question": "Un type d''unité précis à voir en priorité ?", "type": "text"}]'::jsonb, 'C''est noté [nom]. Je vous confirme le rendez-vous par WhatsApp avec l''adresse et un plan d''accès. À très bientôt !', TRUE),
  ('visite_confirmee', 'Visite confirmée — Rappel & confirmation (J-1)', 'Bonjour [nom], [agent] de [agence]. Petit rappel pour notre visite prévue prochainement. Je voulais m''assurer que tout est bon de votre côté.', '[{"id": "q1", "question": "Vous confirmez bien votre présence ?", "type": "radio", "options": ["Oui, confirmé", "À reporter", "Annuler"], "conditions": [{"if": "À reporter", "then_say": "Pas de problème, on trouve un autre créneau. Quel jour vous arrangerait ?"}, {"if": "Annuler", "then_say": "Je comprends. On garde le contact et je reste disponible quand vous voudrez."}, {"if_default": true, "then_say": "Parfait, on vous attend !"}]}, {"id": "q2", "question": "Vous avez bien reçu l''adresse et le plan d''accès ?", "type": "radio", "options": ["Oui", "Non, à renvoyer"]}, {"id": "q3", "question": "Documents à préparer pour la visite ?", "type": "checkbox", "options": ["Plans 2D", "Grille de prix", "Simulation de paiement", "Disponibilités"]}, {"id": "q4", "question": "Combien serez-vous de personnes ?", "type": "number"}]'::jsonb, 'Parfait [nom], on vous attend. Je prépare tout. Appelez-moi en cas d''imprévu — à demain !', TRUE),
  ('visite_terminee', 'Visite terminée — Feedback à chaud', 'Bonjour [nom], [agent] de [agence]. Merci d''être venu visiter ! Je voulais recueillir votre ressenti à chaud, tant que c''est frais.', '[{"id": "q1", "question": "Globalement, qu''avez-vous pensé du bien ?", "type": "radio", "options": ["Très intéressé", "Intéressé mais hésitant", "Mitigé", "Pas convaincu"], "maps_to": "interest_level", "conditions": [{"if": "Très intéressé", "then_say": "Excellent ! On peut sécuriser l''unité avec une réservation avant qu''elle parte. Je vous explique ?"}, {"if": "Pas convaincu", "then_say": "Merci pour votre franchise. Qu''est-ce qui n''allait pas, pour que je vous propose mieux ?"}, {"if_default": true, "then_say": "Je note. Voyons ensemble ce qui vous ferait franchir le pas."}]}, {"id": "q2", "question": "Qu''est-ce qui vous a le plus plu ?", "type": "checkbox", "options": ["Emplacement", "Surface", "Prix", "Finitions", "Vue", "Luminosité", "Agencement", "Parking"]}, {"id": "q3", "question": "Des points qui vous freinent ?", "type": "text"}, {"id": "q4", "question": "Le prix correspond-il à votre budget ?", "type": "radio", "options": ["Oui", "Un peu élevé", "Trop élevé"], "conditions": [{"if": "Un peu élevé", "then_say": "On peut regarder les facilités de paiement, ou une autre unité. Je vous fais une simulation."}, {"if": "Trop élevé", "then_say": "Je comprends. Laissez-moi vous proposer une unité plus adaptée à votre budget."}]}, {"id": "q5", "question": "Quelle est la prochaine étape pour vous ?", "type": "radio", "options": ["Réserver", "Réfléchir quelques jours", "Comparer d''autres biens"]}]'::jsonb, 'Merci [nom] pour ce retour. Je vous envoie une simulation personnalisée par WhatsApp. Si le cœur y est, on peut bloquer l''unité — elles partent vite.', TRUE),
  ('negociation', 'Négociation — Lever les objections & closer', 'Bonjour [nom], [agent] de [agence]. Je vous appelle pour avancer sur votre projet. Je sais que le bien vous intéresse — voyons ce qu''on peut faire ensemble.', '[{"id": "q1", "question": "Qu''est-ce qui vous retient de finaliser aujourd''hui ?", "type": "radio", "options": ["Le prix", "Le financement", "Le timing", "Un doute sur le bien", "Je compare encore"], "conditions": [{"if": "Le prix", "then_say": "Le prix est négociable sur les conditions. Parlons facilités de paiement et échéancier adapté."}, {"if": "Le financement", "then_say": "On a des solutions d''échelonnement promoteur et des partenaires bancaires. Je vous accompagne sur le montage."}, {"if": "Je compare encore", "then_say": "C''est sain de comparer. Sur quels critères ? Je vous montre pourquoi notre offre est la meilleure sur ce point."}, {"if_default": true, "then_say": "Dites-m''en plus, on va trouver une solution ensemble."}]}, {"id": "q2", "question": "Quel budget seriez-vous prêt à engager (en DA) ?", "type": "number", "maps_to": "confirmed_budget"}, {"id": "q3", "question": "Quel mode de financement privilégiez-vous ?", "type": "select", "options": ["Comptant", "Crédit bancaire", "Mixte", "Échelonné promoteur"], "maps_to": "payment_method"}, {"id": "q4", "question": "Si je trouve un arrangement sur les conditions, seriez-vous prêt à réserver cette semaine ?", "type": "radio", "options": ["Oui", "Peut-être", "Non"]}]'::jsonb, 'Je note tout ça [nom]. Je vois avec ma direction ce qu''on peut faire sur les conditions, et je reviens vers vous très vite. L''objectif, c''est que vous repartiez avec votre bien.', TRUE),
  ('reservation', 'Réservation — Sécuriser le dépôt & le dossier', 'Bonjour [nom], félicitations pour votre choix ! [agent] de [agence]. On finalise votre réservation — je vous explique les étapes, c''est simple et rapide.', '[{"id": "q1", "question": "Avez-vous votre pièce d''identité (NIN / CIN) prête pour le dossier ?", "type": "radio", "options": ["Oui", "Je l''envoie aujourd''hui", "Pas encore"], "conditions": [{"if": "Pas encore", "then_say": "Pas de souci, une photo nette par WhatsApp suffit pour démarrer le dossier."}]}, {"id": "q2", "question": "Comment souhaitez-vous régler l''acompte ?", "type": "select", "options": ["Espèces", "Virement bancaire", "Chèque"]}, {"id": "q3", "question": "Pour quelle durée de réservation ?", "type": "radio", "options": ["15 jours", "30 jours", "60 jours"]}, {"id": "q4", "question": "Des questions sur le contrat ou l''échéancier ?", "type": "text"}]'::jsonb, 'Parfait [nom]. Je prépare le bon de réservation et je vous envoie la liste des documents par WhatsApp. On se voit au bureau pour signer ?', TRUE),
  ('relancement', 'Relancement — Réchauffer un lead', 'Bonjour [nom], [agent] de [agence]. Ça fait un moment qu''on ne s''est pas parlé ! Je reviens vers vous car on a du nouveau qui pourrait vous intéresser.', '[{"id": "q1", "question": "Votre projet immobilier est-il toujours d''actualité ?", "type": "radio", "options": ["Oui, toujours", "En pause", "Plus d''actualité"], "conditions": [{"if": "En pause", "then_say": "Aucun souci. Quand pensez-vous reprendre ? Je note pour vous recontacter au bon moment."}, {"if": "Plus d''actualité", "then_say": "Merci de me l''avoir dit. Je vous recontacterai uniquement si une opportunité exceptionnelle se présente."}, {"if_default": true, "then_say": "Super, alors voyons ce qui a changé depuis la dernière fois."}]}, {"id": "q2", "question": "Qu''est-ce qui vous avait freiné la dernière fois ?", "type": "checkbox", "options": ["Prix", "Financement", "Timing", "Localisation", "Pas trouvé le bon bien"]}, {"id": "q3", "question": "Vos critères ont-ils changé (budget, type, zone) ?", "type": "text"}, {"id": "q4", "question": "Je vous envoie nos dernières disponibilités ?", "type": "radio", "options": ["Oui, par WhatsApp", "Oui, par email", "Non merci"]}]'::jsonb, 'Content d''avoir repris contact [nom]. Je vous envoie une sélection adaptée à votre budget. Et si vous voulez, on cale une visite — sans engagement.', TRUE),
  ('vente', 'Vente — Suivi post-achat, fidélisation & parrainage', 'Bonjour [nom], [agent] de [agence]. Encore toutes mes félicitations pour votre acquisition ! Je voulais prendre de vos nouvelles et m''assurer que tout se passe bien.', '[{"id": "q1", "question": "Tout est clair concernant votre échéancier de paiement ?", "type": "radio", "options": ["Oui", "J''ai une question", "Non"]}, {"id": "q2", "question": "Êtes-vous satisfait du suivi de votre dossier ?", "type": "radio", "options": ["Très satisfait", "Satisfait", "Des points à améliorer"]}, {"id": "q3", "question": "Connaissez-vous quelqu''un qui cherche aussi un bien ?", "type": "radio", "options": ["Oui", "Peut-être", "Non"], "conditions": [{"if": "Oui", "then_say": "Génial ! On a un programme de parrainage avantageux — je vous envoie les détails, ça récompense tout le monde."}]}, {"id": "q4", "question": "Souhaitez-vous être informé de nos prochains programmes ?", "type": "radio", "options": ["Oui", "Non"]}]'::jsonb, 'Merci [nom] pour votre confiance. Vous avez mon numéro direct pour toute question. Et pensez au parrainage — c''est tout bénéf'' pour vous !', TRUE),
  ('perdue', 'Perdue — Récupération & retour d''expérience', 'Bonjour [nom], [agent] de [agence]. Je me permets un dernier appel. On n''a pas pu concrétiser ensemble, et je voulais comprendre pourquoi — ça m''aide à m''améliorer.', '[{"id": "q1", "question": "Qu''est-ce qui a fait que ça ne s''est pas fait ?", "type": "radio", "options": ["Prix trop élevé", "Acheté ailleurs", "Mauvais timing", "Localisation", "Problème de financement", "Changement de projet"]}, {"id": "q2", "question": "Avez-vous finalement acheté ailleurs ?", "type": "radio", "options": ["Oui", "Non, toujours en recherche", "Projet abandonné"], "conditions": [{"if": "Non, toujours en recherche", "then_say": "Alors tout n''est pas perdu ! Laissez-moi une dernière chance de vous proposer quelque chose de vraiment adapté."}]}, {"id": "q3", "question": "Si j''avais une offre adaptée à votre budget, seriez-vous ouvert à en rediscuter ?", "type": "radio", "options": ["Oui", "Peut-être plus tard", "Non"]}, {"id": "q4", "question": "Un conseil pour qu''on s''améliore ?", "type": "text"}]'::jsonb, 'Merci [nom] pour votre honnêteté, ça m''aide beaucoup. Je garde votre profil : si une opportunité en or se présente, vous serez le premier informé. Bonne continuation !', TRUE);

NOTIFY pgrst, 'reload schema';

-- Vérification.
SELECT pipeline_stage, title, jsonb_array_length(questions) AS nb_questions
  FROM public.call_scripts WHERE is_active = TRUE ORDER BY pipeline_stage;

COMMIT;
